# Generated by Django 4.2.5 on 2024-01-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_openid', models.CharField(blank=True, db_comment='微信小程序的登录API返回的用户唯一标识符', max_length=45, null=True, unique=True)),
                ('user_session_key', models.CharField(blank=True, db_comment='微信小程序的登录API返回的本次登录的会话密钥', max_length=45, null=True, unique=True)),
                ('user_token', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'tb_user',
                'db_table_comment': '用户基本信息表',
                'managed': False,
            },
        ),
    ]
